[platformio]
default_envs = esp32c3

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
  -I.
  -DBENCH_ITERS=1000
  -DBENCH_TIMEOUT_US=2000000
  -DBENCH_WARMUP_ITERS=64
